### ISSUE TITLE
filter special characters from incoming FT filenames

### ISSUE THREAD

**Issue by zoff99** [TokTok/toxic#111]
filter '/' and '\\' and '..' from incoming filename

https://github.com/TokTok/toxic/blob/a86884c40e0ece8c514360b93d93087eac69aeec/src/chat.c#L622

https://github.com/TokTok/toxic/blob/a86884c40e0ece8c514360b93d93087eac69aeec/src/chat.c#L622

**Comment by JFreegman** [comment]
What's wrong with `..`?

**Comment by zoff99** [comment]
because when the filename is
```'/../../../../../../../../../../../../home/jfreegman/.bashrc'```
then not matter what directory you prefix it with, it may write a nice .bashrc in your homedir with some sudo commands in it, if you don't have a .bashrc yet

**Comment by JFreegman** [comment]
Ok, that problem is solved by not allowing the `/` character.
